draft PR
USTC-vlab/docs pull request #8
Opened 2024-09-25 04:27 UTC by Ack508

前两个问题的书写已完成

2024-09-25 07:01 UTC, iBug reviewed
考虑到你这里添加了超过 20 张图片，给它们额外建个文件夹会更整洁（i.e. `images/*.png` → `images/vscode2vlab/*.png`）

2024-09-25 07:06 UTC, iBug commented on docs/vscode2vlab.md
> +进入 Vivado 后，点击 ***Create Project***:
本文***大量***使用了加粗斜体（`***`），大多数情况下这是没有必要的。如果是引用按钮上的文字的话，加粗（`**`）足够了，或者使用「中文括号」或【中文括号】也行。

2024-09-26 04:53 UTC, Ack508 commented on docs/vscode2vlab.md
> +进入 Vivado 后，点击 ***Create Project***:
first提交的对于两个问题在third提交中已经修改，third提交中已完成了文档的4/6

2024-09-26 05:29 UTC, taoky commented on docs/vscode2vlab.md
> +显示的ctags信息是universal ctags，说明安装正常。
建议在本地装一下 <https://github.com/huacnlee/autocorrect/>，这样可以在保存时自动纠正一些格式问题。

有 VSCode 插件：<https://marketplace.visualstudio.com/items?itemName=huacnlee.autocorrect>

2024-09-26 05:53 UTC, iBug commented on docs/vscode2vlab.md
>  这样我们就可以在 vscode 中进行 verilog 的开发了！
可以全文过一遍，把 VSCode Verilog 这些专有名词的大小写统一一下

2024-09-26 15:31 UTC, iBug requested changes

2024-09-26 15:31 UTC, iBug commented on docs/vscode2vlab.md
> +# 本地 VSCode 通过 Remote SSH 连接 Vlab
H1 前面留一个空行

2024-09-26 15:31 UTC, iBug commented on docs/vscode2vlab.md
> +
这里也不需要两个空行，一个就够

2024-09-26 15:31 UTC, iBug commented on docs/vscode2vlab.md
> +在虚拟机的桌面上，最上面**应用程序**中的** Vlab 实验软件**里可找到预先安装的的 Vivado，点击进入 Vivado。这里请大家选择 2019.1 版本，不要选择 2016.3 的旧版本。2023.1 版本的 Vivado 虽然更便捷，但可能引起内存不足的警告，因此请大家酌情使用。
`中的** Vlab 实验软件` 空格位置是不是不对

2024-09-26 15:31 UTC, iBug commented on docs/vscode2vlab.md
> +进入 VSCode 的[官方网站](https://code.visualstudio.com/)，点击 Download for Windows 下载。下载完成后打开可执行文件。在**选择附加任务**时建议全部勾选，特别是**添加到 PATH **要勾选，否则后续还要自己将其添加到环境变量。
`添加到 PATH **要勾选`

2024-09-26 15:31 UTC, iBug commented on docs/vscode2vlab.md
> +    - CTRL 鼠标点击跳转到代码声明
`CTRL` → `Ctrl`

2024-09-26 15:31 UTC, iBug commented on docs/vscode2vlab.md
> +目前我们已经安装了 Verilog-HDL/SystemVerilog 插件，但还需要安装 **iverilog(一种 linter)** 和 **ctags**。
`iverilog(一种 linter)` → `iverilog（一种 linter）`（使用中文括号）

2024-09-26 15:31 UTC, iBug commented on docs/vscode2vlab.md
> +    对于 verilog 的 linter 当然不止一种，本教程中使用的是 iverilog。除此之外还有 xvlog 和 Verilator，但 xvlog 来自于 **vivado**，你需要在电脑本地安装 vivado 才有 xvlog。而 Verilator 则是面向 linux 平台开发的，截至目前使用官网方法在 Windows 平台上编译的 Verilator 都无法配合 VSC
- vivado → Vivado
- linux → Linux

2024-09-26 15:31 UTC, iBug commented on docs/vscode2vlab.md
> +按下面的设置配置 ctags，将 linter 选择为 iverilog，并在 Iverilog 的 Argument 一栏中加入 -i 参数。
需要统一一下大小写，iverilog 还是 Iverilog

2024-09-26 15:31 UTC, iBug commented on docs/vscode2vlab.md
> +    由于在安装 ctags 时已经将其加入到了环境变量，所以这里只需填入 ctags 即可。关于 -i 参数，是因为在实例化模块时 iverilog 会报错 "Unknown module type"，添加 "-i" 参数可以避免这种不合理的报错。
`"-i"` → `` `-i` ``

2024-09-26 15:31 UTC, iBug commented on docs/vscode2vlab.md
> +##  SSH 通过命令行远程连接 Vlab {#ssh2vlab}
这一段完全重复的内容就不要复制了吧，直接引用来源页面

2024-09-26 15:31 UTC, iBug commented on docs/vscode2vlab.md
> +我们也可以用快捷键 **Ctrl + `** 打开终端，此时的终端环境是 Vlab 的，可以通过命令行对 Vlab 进行操作。
`` ` `` 在 Markdown 里最好转义

2024-09-26 15:31 UTC, iBug commented on docs/vscode2vlab.md
> +我们要在 Vlab 中安装 ctags 和 iverilog(和 gtkwave)。在 **Vlab 虚拟机** 中打开终端，执行以下命令：
这几个 code block 可以合成一个，apt install 命令也可以合成一个

另：现在一般推荐用 `apt` 代替 `apt-get`

2024-09-26 15:31 UTC, iBug commented on docs/vscode2vlab.md
> +然后在 VSCode 已打开的远程连接 Vlab 中打开 Verilog-HDL/SystemVerilog 的扩展设置，将**远程 [SSH:vlab]**和**工作区**中同[本地配置](vscode2vlab.md#configExtention) (即“用户”一栏中的配置) 进行设置。
同一个文件内的链接无需使用文件名，直接 `[](#something)` 即可

2024-09-27 05:20 UTC, Ack508 commented on docs/vscode2vlab.md
> +然后在 VSCode 已打开的远程连接 Vlab 中打开 Verilog-HDL/SystemVerilog 的扩展设置，将**远程 [SSH:vlab]**和**工作区**中同[本地配置](vscode2vlab.md#configExtention) (即“用户”一栏中的配置) 进行设置。
以上这些问题已修改。关于 SSH 远程连接 Vlab 的章节，其实有一些自己的修改，并不是完全复制的，是针对于 Windows 系统的更为详细的操作，包括修改 .pem 的权限如何操作等。所以这个我没有动，其他的都已修改

2024-09-27 05:26 UTC, iBug commented on docs/vscode2vlab.md
> +由于技术限制，每个虚拟机的私钥都是独立的。若你删除并重新创建了虚拟机，你需要重新生成密钥对才能使用密钥登录新的虚拟机。
看起来从 `SSH 通过命令行远程连接 Vlab` 这个标题到这里都是直接从 ssh 帮助页面复制过来的，不建议这样大段的复制粘贴（如果以后有修订，需要同时修改两处，容易出现错乱），最好改成一句“请参考 xxx 页面的 xxx 章节”并给出 `[](ssh.md#something)` 的跳转链接。

2024-09-27 06:38 UTC, taoky commented on docs/vscode2vlab.md
> +然后在 VSCode 已打开的远程连接 Vlab 中打开 Verilog-HDL/SystemVerilog 的扩展设置，将**远程 [SSH:vlab]**和**工作区**中同[本地配置](vscode2vlab.md#configExtention) (即“用户”一栏中的配置) 进行设置。
> 以上这些问题已修改。关于 SSH 远程连接 Vlab 的章节，其实有一些自己的修改，并不是完全复制的，是针对于 Windows 系统的更为详细的操作，包括修改 .pem 的权限如何操作等。所以这个我没有动，其他的都已修改

那可以直接去改 ssh.md？

2024-09-27 08:39 UTC, Ack508 commented on docs/vscode2vlab.md
> +由于技术限制，每个虚拟机的私钥都是独立的。若你删除并重新创建了虚拟机，你需要重新生成密钥对才能使用密钥登录新的虚拟机。
已修改

2024-09-27 08:49 UTC, taoky commented on docs/vscode2vlab.md
> +    对于 verilog 的 linter 当然不止一种，本教程中使用的是 iverilog。除此之外还有 xvlog 和 Verilator，但 xvlog 来自于 **vivado**，你需要在电脑本地安装 Vivado 才有 xvlog。而 Verilator 则是面向 Linux 平台开发的，截至目前使用官网方法在 Windows 平台上编译的 Verilator 都无法配合 VSC
这里的拼写需要修正一下。另外对新手来说，是不是简单说一下 linter 的概念会更好？

2024-09-27 08:50 UTC, taoky commented on docs/vscode2vlab.md
> +我们将私钥放在 `%UserProfile%\.ssh` 目录中，例如 `%UserProfile%\.ssh\vlab.pem`。
对于新手来说，可能需要讲一下 `%UserProfile%` 是什么东西。

2024-09-27 16:20 UTC, Ack508 commented on docs/vscode2vlab.md
> +我们将私钥放在 `%UserProfile%\.ssh` 目录中，例如 `%UserProfile%\.ssh\vlab.pem`。
已修改

2024-09-27 16:48 UTC, iBug commented on docs/vscode2vlab.md
> +    **linter** 是自动检查源代码中是否存在编程和样式错误的工具。对于 Verilog 的 linter 当然不止一种，本教程中使用的是 iverilog。除此之外还有 xvlog 和 Verilator，但 xvlog 来自于 **Vivado**，你需要在电脑本地安装 Vivado 才有 xvlog。而 Verilator 则是面向 Linux 平台开发的，截至目前使用官网方法在
英文单词位于句首需要首字母大写

2024-09-27 16:48 UTC, iBug commented on docs/vscode2vlab.md
> +    **%UserProfile%** 是用户目录，即**C:\Users（用户）\用户登陆名**。`vlab.pem` 文件的完整路径例如 `C:\Users\Asus\.ssh\vlab.pem`。
建议对 `%UserProfile%` 使用 `` ` ` `` 代码格式

2024-09-28 04:34 UTC, Ack508 commented on docs/vscode2vlab.md
> +    **%UserProfile%** 是用户目录，即**C:\Users（用户）\用户登陆名**。`vlab.pem` 文件的完整路径例如 `C:\Users\Asus\.ssh\vlab.pem`。
已修改

2024-09-28 06:35 UTC, iBug commented on docs/vscode2vlab.md
> +```
使用 ` ``` ` 创建的 code block 前后都需要有一个空行，这个 code block 的后面没有空行。

另：如果你安装了 Markdownlint 或者它的 VSCode 插件（[`davidanson.vscode-markdownlint`](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)）的话，这类问题是能够自动检测出来的

2024-09-28 06:35 UTC, iBug commented on docs/vscode2vlab.md
> +```
推荐对所有 code block 都指明 language，如果不需要任何语法高亮的话，可以指定 ` ```text `

2024-09-28 06:36 UTC, iBug commented on docs/vscode2vlab.md
> +```
code block 后的空行问题，同

2024-09-28 06:41 UTC, iBug commented on docs/vscode2vlab.md
> +### 4. 配置 Verilog-HDL/SystemVerilog 插件 {#configExtention}
一般 URL 设计中不会使用大写字母，单词之间用 `-` 分隔（另外 extension 也拼错了）

注意本文下面某处有一个对此标题的引用

2024-09-28 07:20 UTC, iBug approved these changes
我感觉差不多了，现在看起来非常好

2024-09-28 07:23 UTC, Ack508 commented
刚有个小的改动，放到new finish了

2024-09-28 07:50 UTC, taoky approved these changes

2024-09-28 07:59 UTC, iBug approved these changes

2024-09-28 08:06 UTC, iBug commented
merge 前最后一件事，给这个 PR 起一个有意义的 title，它会作为 merge commit 的 message

> ![image](https://github.com/user-attachments/assets/4205d967-a43c-4de9-a428-fe6bc31d9640)

2024-09-28 08:16 UTC, merged